[[plugins]] repo = 'billyvg/tigris.nvim'
on_ft = ['javascript', 'javascript.jsx']
hook_add = '''
let g:tigris#enabled = 1
let g:tigris#on_the_fly_enabled = 1
let g:tigris#delay = 300
'''

hook_post_update = '''
let g:dein#plugin.build = './install.sh'
'''
